name: frontend

on:
  push:
    branches: [ master, develop ]
    paths:
    - 'frontend/**'
    - '.github/workflows/frontend.yml'

 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy
      env:
        CICD: "*"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GOOGLE_POOL_ID_PROD: ${{ secrets.GOOGLE_POOL_ID_PROD }}
        GOOGLE_POOL_SECRET_PROD: ${{ secrets.GOOGLE_POOL_SECRET_PROD }}
        GOOGLE_POOL_ID_DEV: ${{ secrets.GOOGLE_POOL_ID_DEV }}
        GOOGLE_POOL_SECRET_DEV: ${{ secrets.GOOGLE_POOL_SECRET_DEV }}
      run: ./deploy-frontend.sh -e ${GITHUB_REF##*/}
        